name: Python package
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10"]
        pytorch-version: ["1.11", "1.12", "1.13"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install mypy pytest pytest-cov tqdm
        pip install torch==${{ matrix.pytorch-version }}
    - name: mypy
      if: ${{ matrix.pytorch-version == '1.13' }}
      run: |
        mypy --install-types --non-interactive .
    - name: pytest
      if: ${{ matrix.pytorch-version == '1.13' }}
      run: |
        pytest --cov=torchinfo --cov-report= --durations=0
    - name: pytest
      if: ${{ matrix.pytorch-version != '1.13' }}
      run: |
        pytest
    - name: codecov
      uses: codecov/codecov-action@v1
